try {
    const m = 1;
    const n = m + z;
} catch (err) {
    console.log(err, err.message)
}